# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone https://github.com/MACHANDRA11/cloudbuild_1_repo.git
    git remote -v
    git config --global user.name "MACHANDRA11"
    git config --global user.email "chandrakanth.maddana@mediaagility.com"
    git config --list
    cp -r tf_template_file tf_copy
    ls 
    cd tf_copy
    cat terraform.tfvars | sed -e "s/gcp_project_id/$_NAME_1/g" >terraform1.tfvars | mv terraform1.tfvars terraform.tfvars
    ls
    cat terraform.tfvars | sed -e "s/gcp_bucket_names/$_NAME_2/g" >terraform1.tfvars | mv terraform1.tfvars terraform.tfvars
    cat terraform.tfvars | sed -e "s/gcp_bucket_prefix/$_NAME_3/g" >terraform1.tfvars | mv terraform1.tfvars terraform.tfvars
    ls
    cat main.tf
    echo "Pushing changes to git config repo ..."
    ls /root/
    git add -A
    git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
    
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd tf_copy
      echo "branch $BRANCH_NAME"
      echo "run init"
      terraform init
      echo "run validate"
      terraform validate 
      echo "run plan"
      terraform plan -out terraform.plan
      terraform apply -auto-approve terraform.plan
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/git-secret-key/versions/latest
    env: 'SSH_KEY'

substitutions:
  _NAME_1: $PROJECT_ID # default value
  _NAME_2: thgsx3ws12
  _NAME_3: tfg




# Access the id_github file from Secret Manager, and setup SSH
# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args: ['a.sh']
#   env:
#     - 'Name=chandra'
  # substitutions:
  #   _NAME: v6.9.1 # default value
# steps:
# - name: ubuntu
#   entrypoint: bash
#   args:
#   - -c
#   - |
#     chmod +x a.sh &&
#     sh a.sh
#   env:
#     - 'Name=${_NAME}'
  # substitutions:
  #   _NAME: v6.9.1 # default value

# steps:
# - name: ubuntu
#   entrypoint: bash
#   args: 
#    - -c 
#    - |
#      # Installing zip executable
#      apt install zip &&
#      zip -r myfiles.zip package/utils &&
#      ls -l /workspace/*

# # Access the id_github file from Secret Manager, and setup SSH
# steps:
# - name: 'gcr.io/cloud-builders/git'
#   secretEnv: ['SSH_KEY']
#   entrypoint: 'bash'
#   args:
#   - -c
#   - |
#     echo "$$SSH_KEY" >> /root/.ssh/id_rsa
#     chmod 400 /root/.ssh/id_rsa
#     cp known_hosts.github /root/.ssh/known_hosts
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# # Clone the repository
# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - clone
#   - --recurse-submodules
#   - git@github.com:GIT_USERNAME/GIT_REPOSITORY
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
  
# - name: gcr.io/cloud-builders/git
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     echo "Cloning repo ..."
#     git clone --depth 1 git@github.com:mikesparr/gcp-cicd-demo-config
#     echo "Updating image tag version ..."
#     cd gcp-cicd-demo-config
#     ls
#     sed -i "s|newTag: .*|newTag: $SHORT_SHA|" demo-app/overlays/develop/kustomization.yaml
#     echo "Pushing changes to git config repo ..."
#     git config --global user.name mikesparr
#     git config --global user.email msparr@gmail.com
#     git add -A
#     git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
#     git push origin master
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
# # for substitution
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build',
#          '--build-arg',
#          'node_version=${_NODE_VERSION_2}',
#          '-t',
#          'gcr.io/$PROJECT_ID/build-substitutions-nodejs-${_NODE_VERSION_2}',
#          '.']
# substitutions:
#     _NODE_VERSION_1: v6.9.1 # default value
#     _NODE_VERSION_2: v6.9.2 # default value

# availableSecrets:
#   secretManager:
#   - versionName: projects/PROJECT_ID/secrets/secret-name/versions/latest
#     env: 'SSH_KEY'








# # cat abc.txt | xargs printStrings.sh
# export TF_VAR_region=us-west-1